# Generated by Django 5.0.3 on 2024-03-28 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItems',
            new_name='OrderItem',
        ),
    ]
